name cpu_intensive_mixed_load
comment long CPU bursts followed by short IO bursts and mixed load in which neither IO nor CPU bursts predominate in parallel
algorithm SJF
seed 5000
numprocs 5
firstarrival 0.0
interarrival constant 0.0
duration constant 40.0
cpuburst constant 10.0
ioburst exponential 1.5
basepriority 1.0

numprocs 5
firstarrival 0.0
interarrival constant 0.0
duration constant 20.0
cpuburst uniform 1.0 5.0
ioburst uniform 1.0 5.0
basepriority 1.0