name cpu_intensive_interactive
comment mixed load in which neither IO nor CPU bursts predominate and use a series of short CPU-bursts followed by a varying waiting time in parallel
algorithm SJF
seed 5000
numprocs 5
firstarrival 0.0
interarrival constant 0.0
duration constant 20.0
cpuburst uniform 1.0 5.0
ioburst uniform 1.0 5.0
basepriority 1.0

numprocs 5
firstarrival 0.0
interarrival constant 0.0
duration constant 5.0
cpuburst constant 0.5
ioburst uniform 1.0 5.0
basepriority 1.0